In [1]:
import pandas as pd

In [2]:
# CSV to Dataframe:
df = pd.read_csv('companies.csv')

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5536 entries, 0 to 5535
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Company                   5535 non-null   object
 1   Company LinkedIn          1802 non-null   object
 2   Company Location (State)  2600 non-null   object
 3   Employee Size             5536 non-null   object
 4   Industry                  5257 non-null   object
 5   Phone                     748 non-null    object
 6   Revenue                   3016 non-null   object
 7   Website                   5377 non-null   object
dtypes: object(8)
memory usage: 346.1+ KB
None

In [4]:
# Print first 5 rows: 
print(df.head(5))

                        Company                           Company LinkedIn  \
0                    13WHAM ABC                                        NaN
1                    13WHAM ABC  http://www.linkedin.com/company/13wham-tv
2  20/20 CUSTOM MOLDED PLASTICS                                        NaN
3  20/20 CUSTOM MOLDED PLASTICS  https://www.linkedin.com/company/15516558
4                     3 UNDER 3                                        NaN

  Company Location (State) Employee Size                Industry Phone  \
0                      NaN            79        Media Production   NaN
1                      NaN            79        Media Production   NaN
2                      NaN     501-1,000  Plastics Manufacturing   NaN
3                     Ohio     501-1,000  Plastics Manufacturing   NaN
4                      NaN           one                     NaN   NaN

  Revenue              Website
0     NaN  https://13wham.com/
1     NaN  https://13wham.com/
2     58M   http://2020cmp.com
3     58M   http://2020cmp.com
4     NaN                  NaN

In [5]:
# Print last 5 rows: 
print(df.tail(5))

                                                Company  \
5531                                               ZOLL
5532                                            ZUMBIEL
5533                                            ZUMBIEL
5534                                                NaN
5535  Applied filters:\nCompany Count is greater tha...

                                       Company LinkedIn  \
5531  https://www.linkedin.com/company/zoll-medical-...
5532                                                NaN
5533                                                NaN
5534                                                NaN
5535                                                NaN

     Company Location (State) Employee Size                         Industry  \
5531            Massachusetts   1,001-5,000  Medical Equipment Manufacturing
5532                      NaN           161           Packaging & Containers
5533                 Kentucky           161           Packaging & Containers
5534                      NaN          four                              NaN
5535                      NaN           ten                              NaN

     Phone   Revenue                Website
5531   NaN   $457.6M  https://www.zoll.com/
5532   NaN  30402000            zumbiel.com
5533   NaN  30402000            zumbiel.com
5534   NaN       NaN                    NaN
5535   NaN       NaN                    NaN

In [6]:
# Display all columns:
print(df.columns)

Index(['Company', 'Company LinkedIn', 'Company Location (State)',
       'Employee Size', 'Industry', 'Phone', 'Revenue', 'Website'],
      dtype='object')

In [7]:
# Change display max width:
pd.set_option('display.max_columns', None)
df.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,13WHAM ABC,NaN,NaN,79,Media Production,NaN,NaN,https://13wham.com/
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,NaN,79,Media Production,NaN,NaN,https://13wham.com/
2,20/20 CUSTOM MOLDED PLASTICS,NaN,NaN,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,NaN,58M,http://2020cmp.com
4,3 UNDER 3,NaN,NaN,one,NaN,NaN,NaN,NaN

In [61]:
# Fill all 'NaN' with 0:
df_clean = df.fillna(0)
df_clean.drop_duplicates(inplace= True)

In [62]:
rev_empty = df[df['Revenue'].isna()]

In [ ]:
# Drop duplicates:

In [63]:
df_clean.reset_index(inplace=True)
df_clean.drop(columns=['index'],inplace=True)
df_clean.head()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
0,13WHAM ABC,0,0,79,Media Production,0,0,https://13wham.com/
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,0,79,Media Production,0,0,https://13wham.com/
2,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
3,20/20 CUSTOM MOLDED PLASTICS,https://www.linkedin.com/company/15516558,Ohio,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com
4,3 UNDER 3,0,0,one,0,0,0,0

In [64]:
df_clean.tail()

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website
5513,ZOLL,https://www.linkedin.com/company/zoll-medical-...,Massachusetts,"1,001-5,000",Medical Equipment Manufacturing,0,$457.6M,https://www.zoll.com/
5514,ZUMBIEL,0,0,161,Packaging & Containers,0,30402000,zumbiel.com
5515,ZUMBIEL,0,Kentucky,161,Packaging & Containers,0,30402000,zumbiel.com
5516,0,0,0,four,0,0,0,0
5517,Applied filters:\nCompany Count is greater tha...,0,0,ten,0,0,0,0

In [65]:
df_clean.count()

Company                     5518
Company LinkedIn            5518
Company Location (State)    5518
Employee Size               5518
Industry                    5518
Phone                       5518
Revenue                     5518
Website                     5518
dtype: int64

In [66]:
df_clean['Revenue'] = df_clean['Revenue'].astype(str)

In [67]:
# Transformed 'Revenue' field to a numeric format and created a new field 'revenue_cleaned'
          
revenue_new = []                                 
for i in range(len(df_clean['Revenue'])):                 
    if (df_clean['Revenue'][i] == '0'):
        revenue_new.append(df_clean['Revenue'][i])
    else:
        if (df_clean['Revenue'][i][-1] == 'M'):                            
            revenue_new.append(df_clean['Revenue'][i][:-1]+'000000')
        else:
            revenue_new.append(df_clean['Revenue'][i])
print(revenue_new)

['0', '0', '58000000', '58000000', '0', '0', '0', '122200000', '0', '$32.5000000', '0', '0', '65498000', '65498000', '271.6000000', '271.6000000', '0', '271.6000000', '271.6000000', '120.8000000', '120.8000000', '0', '0', '0', '0', '0', '0', '286.1000000', '286.1000000', '35000000', '35000000', '0', '0', '0', '0', '0', '310000000', '310000000', '25000000', '0', '0', '0', '$69.6000000', '0', '$69.6000000', '36.2000000', '0', '36.2000000', '0', '0', '0', '200000000', '200000000', '47000000', '0', '$54000000', '0', '0', '10000000', '10000000', '46.9000000', '46.9000000', '200000000', '200000000', '70000000', '70000000', '42.5000000', '42.5000000', '0', '0', '$75.5000000', '0', '33.8000000', '33.8000000', '26000000', '0', '0', '0', '139000000', '0', '42000000', '42000000', '352700000', '0', '43999000', '43999000', '27900000', '27900000', '107.5000000', '107.5000000', '98200000', '0', '52000000', '0', '52000000', '28000000', '0', '0', '0', '25000000', '0', '0', '0', '0', '0', '0', '35.5000000', '35.5000000', '0', '0', '0', '0', '0', '40000000', '40000000', '188.2000000', '188.2000000', '0', '0', '45000000', '45000000', '25000000', '25000000', '$27.3000000', '0', '0', '117.8000000', '117.8000000', '400000000', '400000000', '36500000', '0', '0', '0', '0', '50000000', '58000000', '58000000', '184600000', '0', '44500000', '0', '27200000', '0', '63.3000000', '63.3000000', '40.3000000', '0', '40.3000000', '50000000', '100000000', '0', '30000000', '30000000', '375000000', '375000000', '$190.1000000', '0', '0', '$274.1000000', '0', '0', '0', '0', '25000000', '0', '38.7000000', '38.7000000', '50000000', '50000000', '33915000', '33915000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '$155.3000000', '0', '0', '0', '0', '0', '45000000', '45000000', '0', '0', '30132000', '30132000', '37500000', '0', '228900000', '228900000', '25000000', '0', '0', '100000000', '32000000', '32000000', '0', '0', '34600000', '0', '39761000', '39761000', '0', '0', '93.8000000', '93.8000000', '0', '0', '40000000', '40000000', '40000000', '40000000', '45.1000000', '45.1000000', '75000000', '75000000', '0', '75000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '98.9000000', '98.9000000', '62000000', '0', '0', '0', '39.1000000', '50000000', '0', '0', '0', '39.1000000', '0', '0', '0', '0', '0', '0', '250000000', '250000000', '64684000', '64684000', '0', '0', '230000000', '0', '0', '0', '42200000', '0', '450000000', '450000000', '82400000', '82.4000000', '82400000', '82.4000000', '65.5000000', '65.5000000', '59.8000000', '59.8000000', '59800000', '59800000', '$31.9000000', '0', '$31.9000000', '40000000', '40000000', '25000000', '0', '$292.3000000', '$292.3000000', '231.5000000', '231.5000000', '40000000', '40000000', '260000000', '0', '0', '0', '0', '0', '85000000', '110000000', '0', '0', '0', '0', '85000000', '450000000', '0', '450000000', '$77.7000000', '$77.7000000', '0', '0', '$217.3000000', '$217.3000000', '$25.0000000', '0', '250000000', '250000000', '150000000', '150000000', '350000000', '350000000', '0', '0', '0', '0', '0', '28600000', '0', '30000000', '30000000', '0', '0', '50000000', '50000000', '50000000', '0', '0', '0', '0', '189900000', '0', '0', '0', '0', '0', '0', '0', '45046000', '45046000', '0', '0', '300000000', '300000000', '300000000', '0', '300000000', '54.8000000', '54.8000000', '59000000', '59000000', '0', '0', '0', '0', '0', '0', '50000000', '50000000', '50000000', '50000000', '$108.6000000', '263400000', '0', '0', '0', '0', '$108.6000000', '44354000', '0', '$61.3000000', '$61.3000000', '53.7000000', '53.7000000', '75000000', '0', '75000000', '1000000000', '0', '0', '55.4000000', '0', '55.4000000', '$34.9000000', '$34.9000000', '63800000', '63800000', '0', '0', '135000000', '135000000', '0', '0', '0', '39000000', '39000000', '246600000', '0', '30.5000000', '30.5000000', '54700000', '0', '0', '0', '0', '0', '0', '0', '0', '103000000', '103000000', '0', '0', '$121.3000000', '0', '40700000', '40700000', '208400000', '208400000', '0', '0', '80000000', '0', '80000000', '35600000', '0', '25996000', '25996000', '150000000', '0', '55000000', '55000000', '250.5000000', '0', '250.5000000', '$26.4000000', '0', '188.4000000', '188.4000000', '75000000', '75000000', '290000000', '290000000', '0', '0', '0', '0', '0', '0', '0', '42.1000000', '42.1000000', '0', '0', '120000000', '0', '120000000', '$497.6000000', '0', '0', '374000000', '374000000', '0', '0', '217.9000000', '217.9000000', '0', '0', '46772000', '0', '40000000', '0', '40000000', '0', '0', '70267000', '0', '0', '0', '63000000', '0', '45000000', '45000000', '91200000', '0', '330.4000000', '330.4000000', '0', '0', '0', '0', '0', '30000000', '30000000', '44.1000000', '44.1000000', '0', '50000000', '0', '0', '0', '0', '0', '0', '19000000', '19000000', '200000000', '0', '40000000', '40000000', '42079000', '0', '42079000', '75000000', '75000000', '$54.3000000', '$54.3000000', '0', '0', '0', '35000000', '35000000', '$53.0000000', '0', '0', '0', '31000000', '31000000', '0', '0', '0', '0', '0', '130600000', '130600000', '$84.5000000', '0', '$84.5000000', '66000000', '66000000', '66000000', '0', '0', '$32.0000000', '0', '45984000', '45984000', '0', '0', '0', '185000000', '185000000', '25000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '300000000', '0', '349999000', '349999000', '0', '0', '0', '0', '60.2000000', '60.2000000', '450000000', '450000000', '85000000', '0', '85000000', '0', '0', '0', '0', '64.6000000', '64.6000000', '$81000000', '$81000000', '59.2000000', '59.2000000', '120000000', '120000000', '0', '0', '0', '0', '0', '0', '68500000', '68500000', '43.4000000', '43.4000000', '20100000', '0', '0', '81700000', '81700000', '14.6000000', '14.6000000', '100000000', '100000000', '63400000', '63400000', '94800000', '0', '0', '0', '0', '$93.7000000', '$93.7000000', '34.7000000', '34.7000000', '0', '0', '$417.4000000', '0', '$417.4000000', '0', '0', '0', '0', '75000000', '75000000', '75000000', '75000000', '75000000', '0', '100000000', '$113.2000000', '$113.2000000', '69.9000000', '0', '69.9000000', '32.4000000', '32.4000000', '5.8000000', '0', '5.8000000', '0', '$41.4000000', '$41.4000000', '47000000', '47000000', '80000000', '80000000', '40904000', '40904000', '85000000', '0', '85000000', '$25000000', '0', '0', '93.4000000', '93.4000000', '0', '0', '35000000', '35000000', '300000000', '0', '300000000', '0', '0', '0', '97.8000000', '97.8000000', '31500000', '0', '0', '0', '$142.6000000', '0', '$142.6000000', '40000000', '40000000', '40000000', '40000000', '12.1000000', '12.1000000', '75000000', '75000000', '0', '0', '0', '0', '0', '0', '0', '$68.4000000', '0', '0', '0', '35.4000000', '0', '35.4000000', '200000000', '200000000', '10000000', '25000000', '0', '345000000', '345000000', '0', '0', '0', '0', '85000000', '85000000', '195900000', '195900000', '0', '0', '0', '0', '0', '0', '0', '0', '58460000', '58460000', '$215.7000000', '0', '$215.7000000', '100000000', '100000000', '100000000', '0', '0', '0', '0', '0', '474100000', '474100000', '25000000', '25000000', '88000000', '88000000', '$75.0000000', '75000000', '40295000', '40295000', '$185.5000000', '0', '$185.5000000', '422500000', '0', '0', '0', '39.6000000', '39.6000000', '225000000', '0', '0', '0', '0', '0', '$176.3000000', '$176.3000000', '36000000', '0', '56.3000000', '56.3000000', '140000000', '0', '0', '0', '218.1000000', '218.1000000', '0', '0', '130.4000000', '0', '130.4000000', '35000000', '0', '33000000', '33000000', '111.9000000', '111.9000000', '0', '0', '0', '0', '85000000', '85000000', '$37000000', '$37000000', '0', '0', '94.5000000', '94.5000000', '61.1000000', '61.1000000', '292000000', '292000000', '30.2000000', '35000000', '0', '0', '0', '0', '30.2000000', '31000000', '31000000', '0', '0', '$54.7000000', '0', '$54.7000000', '$324.4000000', '0', '0', '0', '0', '0', '0', '0', '77.5000000', '77.5000000', '57407000', '57407000', '40000000', '40000000', '0', '0', '0', '0', '51.9000000', '51.9000000', '0', '0', '155000000', '155000000', '0', '155000000', '155000000', '$80.3000000', '0', '$80.3000000', '58.9000000', '58.9000000', '85.2000000', '85.2000000', '$352.8000000', '0', '0', '0', '220000000', '220000000', '0', '0', '0', '0', '57000000', '57000000', '$26.5000000', '0', '111000000', '0', '39599000', '39599000', '70800000', '0', '215500000', '0', '0', '0', '0', '0', '0', '0', '42975000', '43.0000000', '43.0000000', '471.1000000', '471.1000000', '100000000', '100000000', '31398000', '31398000', '84000000', '84000000', '47000000', '47000000', '31.9000000', '31.9000000', '50275000', '50275000', '200000000', '200000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '$34.1000000', '$34.1000000', '28100000', '0', '$79.3000000', '$79.3000000', '107500000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '514400000', '0', '0', '0', '0', '0', '$55.2000000', '0', '$55.2000000', '0', '0', '151.3000000', '151.3000000', '0', '0', '0', '0', '0', '0', '32000000', '32000000', '$25.8000000', '25800000', '40.2000000', '40.2000000', '0', '0', '0', '0', '117.4000000', '117.4000000', '54000000', '0', '20000000', '54000000', '0', '0', '0', '50000000', '37500000', '37500000', '186000000', '186000000', '120000000', '120000000', '32000000', '32000000', '32000000', '32000000', '31006000', '31006000', '75000000', '75000000', '0', '0', '0', '0', '0', '0', '75000000', '$32.6000000', '0', '0', '0', '0', '0', '0', '0', '100000000', '100000000', '25400000', '0', '0', '0', '0', '0', '0', '151448000', '151448000', '300000000', '300000000', '300000000', '83400000', '83400000', '0', '0', '0', '0', '25000000', '0', '0', '0', '0', '0', '122.5000000', '122.5000000', '30000000', '30000000', '46.4000000', '46.4000000', '37.9000000', '37.9000000', '0', '0', '0', '0', '0', '250000000', '250000000', '250000000', '64000000', '64000000', '0', '0', '0', '0', '40.1000000', '40.1000000', '100000000', '0', '10000000', '0', '0', '0', '0', '40000000', '0', '0', '0', '$279.5000000', '0', '$279.5000000', '531800000', '531800000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '473.8000000', '0', '473.8000000', '145515000', '145515000', '42.9000000', '42.9000000', '50756000', '50756000', '75000000', '75000000', '32744000', '32744000', '55038000', '55038000', '0', '0', '$97.3000000', '0', '0', '0', '0', '77.4000000', '77.4000000', '0', '0', '$30.6000000', '0', '39.6000000', '39.6000000', '0', '27103000', '27103000', '0', '50.1000000', '50.1000000', '49455000', '49455000', '117.4000000', '0', '117.4000000', '250000000', '250000000', '$25.0000000', '0', '0', '0', '50000000', '50000000', '$57.9000000', '$57.9000000', '59.3000000', '0', '59.3000000', '32000000', '32000000', '70.7000000', '0', '70.7000000', '0', '0', '41.2000000', '41.2000000', '50000000', '50000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '500000000', '0', '150000000', '150000000', '72300000', '0', '72300000', '0', '0', '74600000', '74600000', '0', '0', '0', '0', '350000000', '350000000', '0', '0', '0', '0', '36.4000000', '0', '36.4000000', '53.8000000', '53.8000000', '73000000', '0', '73000000', '$25000000', '0', '33753000', '0', '0', '0', '52.7000000', '0', '52.7000000', '$127.3000000', '0', '$127.3000000', '40000000', '40000000', '0', '0', '0', '30465000', '30465000', '0', '0', '0', '0', '0', '115000000', '115000000', '150000000', '150000000', '0', '0', '271.6000000', '271.6000000', '298900000', '0', '0', '0', '60000000', '60000000', '$26.6000000', '0', '150000000', '150000000', '0', '0', '0', '0', '44500000', '0', '$122.5000000', '$122.5000000', '$582.0000000', '0', '34.0000000', '34.0000000', '82600000', '82600000', '0', '0', '0', '0', '0', '325.2000000', '325.2000000', '25000000', '0', '0', '218.7000000', '0', '218.7000000', '0', '0', '51000000', '51000000', '150000000', '150000000', '150000000', '133800000', '0', '0', '$50.5000000', '$50.5000000', '78.1000000', '78.1000000', '0', '0', '0', '0', '0', '0', '50000000', '50000000', '0', '0', '25000000', '0', '0', '201.7000000', '201.7000000', '30900000', '0', '0', '0', '450.2000000', '0', '450.2000000', '75000000', '75000000', '0', '0', '0', '0', '65000000', '65000000', '$25.4000000', '0', '0', '0', '56000000', '56000000', '34.1000000', '34.1000000', '35000000', '0', '0', '0', '0', '0', '70000000', '0', '99600000', '0', '0', '166.6000000', '166.6000000', '50000000', '50000000', '300000000', '300000000', '0', '0', '11200000', '11200000', '0', '0', '0', '0', '0', '0', '248000000', '0', '0', '0', '30.3000000', '30.3000000', '247000000', '247000000', '25000000', '0', '0', '0', '0', '0', '0', '49100000', '49100000', '48000000', '48000000', '0', '0', '0', '0', '0', '0', '0', '510500000', '0', '25000000', '0', '46000000', '0', '115000000', '0', '0', '0', '$46.3000000', '0', '0', '104.6000000', '104.6000000', '0', '0', '0', '0', '0', '50000000', '0', '0', '92.7000000', '92.7000000', '168000000', '0', '168000000', '60000000', '0', '98.7000000', '98.7000000', '41.1000000', '41.1000000', '86000000', '0', '140000000', '140000000', '$35.0000000', '0', '$69.6000000', '0', '600000000', '0', '300000000', '300000000', '222500000', '222500000', '131.2000000', '131.2000000', '45793000', '45793000', '0', '0', '0', '86600000', '0', '25000000', '0', '64.3000000', '64.3000000', '57500000', '0', '0', '0', '75000000', '0', '75000000', '54300000', '0', '34.4000000', '0', '34.4000000', '0', '0', '0', '0', '0', '300000000', '0', '300000000', '70000000', '0', '70000000', '$65.6000000', '0', '355.3000000', '0', '355.3000000', '70000000', '70000000', '0', '0', '55900000', '0', '0', '300000000', '300000000', '300000000', '300000000', '0', '530000000', '0', '125000000', '125000000', '0', '0', '76200000', '0', '0', '391000000', '0', '0', '0', '25000000', '25000000', '26900000', '0', '0', '0', '100000000', '100000000', '67.9000000', '0', '67.9000000', '0', '0', '0', '37100000', '0', '70000000', '0', '70000000', '70000000', '0', '0', '90000000', '90000000', '80859000', '80859000', '39000000', '39000000', '0', '0', '125000000', '125000000', '42.7000000', '42.7000000', '37000000', '37000000', '200000000', '200000000', '200000000', '0', '200000000', '0', '0', '0', '0', '0', '0', '33.9000000', '0', '33.9000000', '0', '0', '25000000', '0', '0', '0', '0', '0', '0', '0', '297000000', '0', '0', '0', '30.9000000', '30.9000000', '45000000', '45000000', '95829000', '95829000', '34789000', '34789000', '204499000', '0', '27000000', '27000000', '$37.3000000', '$37.3000000', '$40.2000000', '0', '0', '0', '57.8000000', '57.8000000', '151000000', '151000000', '0', '0', '0', '0', '$54.3000000', '0', '31.0000000', '31.0000000', '31.7000000', '31.7000000', '53.4000000', '0', '53.4000000', '31.0000000', '0', '31.0000000', '51.2000000', '0', '51.2000000', '75000000', '75000000', '53500000', '53500000', '50000000', '30.6000000', '30.6000000', '33.6000000', '0', '33.6000000', '0', '0', '30000000', '30000000', '64.2000000', '64.2000000', '38000000', '38000000', '52.8000000', '52.8000000', '43.9000000', '43.9000000', '200000000', '200000000', '34.8000000', '0', '34.8000000', '114.1000000', '0', '114.1000000', '0', '0', '$72.5000000', '0', '$64.1000000', '0', '150000000', '150000000', '97800000', '97800000', '64.3000000', '64.3000000', '$25000000', '0', '0', '0', '0', '600000000', '600000000', '0', '0', '0', '0', '0', '55000000', '0', '52400000', '0', '0', '0', '0', '0', '0', '0', '0', '430000000', '430000000', '430000000', '25000000', '25000000', '$32.0000000', '0', '0', '0', '0', '51400000', '0', '172.5000000', '172.5000000', '0', '0', '115000000', '115000000', '0', '12600000', '0', '0', '0', '570000000', '570000000', '142500000', '0', '0', '0', '0', '0', '150000000', '150000000', '193.9000000', '193.9000000', '0', '0', '100000000', '100000000', '27700000', '0', '36.4000000', '36.4000000', '38944000', '38944000', '0', '0', '60000000', '60000000', '50.0000000', '50.0000000', '537000000', '0', '200000000', '200000000', '589422000', '589422000', '$590000000', '0', '0', '$32.6000000', '0', '0', '0', '0', '0', '40770000', '40770000', '0', '0', '0', '100000000', '0', '0', '0', '0', '100000000', '500000000', '0', '72400000', '0', '52.8000000', '0', '52.8000000', '0', '0', '0', '0', '47.8000000', '47.8000000', '100000000', '100000000', '0', '0', '72000000', '60000000', '72000000', '0', '60000000', '39000000', '39000000', '0', '0', '70000000', '70000000', '31000000', '0', '150000000', '150000000', '0', '0', '222208000', '0', '75.5000000', '75.5000000', '35000000', '35000000', '$119.2000000', '0', '67600000', '67600000', '130000000', '130000000', '0', '0', '130000000', '75000000', '0', '0', '0', '0', '0', '20000000', '5100000', '5100000', '30000000', '30000000', '0', '0', '0', '0', '116000000', '0', '30000000', '30000000', '70000000', '70000000', '0', '0', '0', '0', '0', '0', '$156.5000000', '0', '63.5000000', '63.5000000', '303000000', '303000000', '258000000', '0', '258000000', '58500000', '0', '100000000', '100000000', '0', '0', '0', '0', '$32.0000000', '0', '26700000', '0', '$191.0000000', '0', '0', '0', '0', '0', '$317.5000000', '$317.5000000', '75000000', '75000000', '50000000', '65000000', '0', '59200000', '0', '0', '0', '172.5000000', '172.5000000', '500000000', '500000000', '0', '62900000', '62900000', '254000000', '0', '254000000', '0', '0', '53.9000000', '53.9000000', '46.5000000', '46.5000000', '75000000', '0', '75000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '390000000', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '159000000', '159000000', '62000000', '62000000', '300000000', '300000000', '$28.0000000', '0', '0', '0', '671400000', '671400000', '30.5000000', '30.5000000', '57000000', '57000000', '290400000', '0', '271.6000000', '271.6000000', '34000000', '34000000', '0', '0', '$33000000', '0', '0', '0', '58.6000000', '58.6000000', '47.7000000', '47.7000000', '0', '0', '61.3000000', '0', '61.3000000', '35000000', '0', '0', '0', '0', '0', '0', '119000000', '0', '0', '30000000', '0', '30000000', '137500000', '0', '0', '0', '0', '0', '32.9000000', '32.9000000', '0', '161000000', '0', '0', '0', '318.3000000', '318.3000000', '100000000', '100000000', '70000000', '70000000', '60000000', '60000000', '0', '0', '33.9000000', '33.9000000', '31.2000000', '31.2000000', '40.3000000', '40.3000000', '0', '0', '37400000', '0', '184.4000000', '184.4000000', '193.8000000', '193.8000000', '0', '100000000', '0', '0', '593600000', '593600000', '493.7000000', '493.7000000', '40000000', '0', '0', '0', '0', '0', '30.1000000', '54.7000000', '0', '30.1000000', '54.7000000', '40964000', '40964000', '0', '0', '65000000', '65000000', '33.7000000', '33.7000000', '0', '0', '319.2000000', '319.2000000', '170000000', '0', '170000000', '150000000', '150000000', '150000000', '150000000', '275000000', '275000000', '0', '0', '59000000', '59000000', '140000000', '140000000', '0', '0', '0', '0', '49900000', '35000000', '35000000', '43.1000000', '0', '43.1000000', '35000000', '35000000', '385.2000000', '385.2000000', '30.7000000', '30.7000000', '31.8000000', '31.8000000', '32.4000000', '32.4000000', '69300000', '$69.3000000', '69300000', '300000000', '300000000', '67400000', '0', '36.8000000', '36.8000000', '53906000', '0', '0', '0', '51200000', '0', '0', '170.5000000', '0', '170.5000000', '$25.0000000', '0', '0', '38005000', '38005000', '0', '0', '44939000', '0', '294.4000000', '4.5000000', '294.4000000', '4.5000000', '37.6000000', '37.6000000', '600000000', '0', '0', '0', '0', '215.9000000', '215.9000000', '0', '0', '0', '0', '0', '37.5000000', '37.5000000', '27800000', '0', '0', '0', '125000000', '125000000', '150000000', '150000000', '0', '0', '0', '0', '31.2000000', '31.2000000', '60700000', '0', '0', '0', '30000000', '30000000', '52000000', '52000000', '448.2000000', '0', '448.2000000', '0', '0', '50000000', '50000000', '210000000', '0', '210000000', '0', '0', '214103000', '214103000', '$30.2000000', '0', '300000000', '300000000', '35000000', '35000000', '232.7000000', '232.7000000', '32436000', '0', '$26000000', '0', '73000000', '73000000', '32080000', '0', '$47000000', '0', '0', '108600000'

In [68]:
df_clean['revenue_cleaned'] = revenue_new
df_clean.head(3)

,Company,Company LinkedIn,Company Location (State),Employee Size,Industry,Phone,Revenue,Website,revenue_cleaned
0,13WHAM ABC,0,0,79,Media Production,0,0,https://13wham.com/,0
1,13WHAM ABC,http://www.linkedin.com/company/13wham-tv,0,79,Media Production,0,0,https://13wham.com/,0
2,20/20 CUSTOM MOLDED PLASTICS,0,0,"501-1,000",Plastics Manufacturing,0,58M,http://2020cmp.com,58000000

In [69]:
pd.set_option('display.max_row', None)
df_clean['revenue_cleaned'].value_counts()

revenue_cleaned
0               2502
100000000         73
50000000          70
40000000          68
75000000          65
300000000         62
35000000          54
25000000          49
70000000          42
150000000         39
30000000          39
200000000         32
60000000          29
250000000         28
32000000          21
80000000          19
400000000         19
500000000         18
45000000          17
55000000          16
120000000         16
65000000          14
450000000         13
125000000         12
31.2000000        12
210000000         12
115000000         11
600000000         11
$25.0000000       11
10000000          11
48000000          10
85000000          10
52000000          10
130000000          9
30.4000000         8
271.6000000        8
58000000           8
345000000          8
43.1000000         8
43000000           8
41.8000000         8
32.1000000         8
90000000           8
59000000           8
51000000           8
328600000          7
31000000           7
39000000           7
36000000           7
220000000          7
38000000           7
140000000          7
47000000           6
170000000          6
37.5000000         6
44.2000000         6
375000000          6
37500000           6
31.1000000         6
315000000          6
56000000           6
155000000          6
31.9000000         6
64000000           6
110000000          6
$25000000          6
32.4000000         6
42.1000000         6
30.5000000         6
105000000          5
62000000           5
27900000           5
26000000           5
66000000           5
33000000           5
72000000           5
57.9000000         4
29000000           4
44000000           4
48.2000000         4
67.6000000         4
31.4000000         4
42.3000000         4
36.2000000         4
63.4000000         4
40.3000000         4
116.1000000        4
71000000           4
63833993           4
42.2000000         4
30.8000000         4
100100000          4
243000000          4
34.2000000         4
180000000          4
97.5000000         4
61.7000000         4
37.6000000         4
135.8000000        4
49.4000000         4
30.1000000         4
258000000          4
33.7000000         4
5100000            4
53.4000000         4
151000000          4
31.0000000         4
38.4000000         4
76.2000000         4
70.9000000         4
52.9000000         4
33.6000000         4
52.8000000         4
34.8000000         4
172.5000000        4
41.7000000         4
37000000           4
230000000          4
33.9000000         4
64.3000000         4
104.6000000        4
168000000          4
51.5000000         4
41.2000000         4
185000000          4
59.3000000         4
131.2000000        4
33.8000000         4
40.1000000         4
36.4000000         4
73000000           4
46.4000000         4
43.0000000         4
54.8000000         4
117.4000000        4
350000000          4
35.4000000         4
57000000           4
39.6000000         4
58.9000000         4
88000000           4
117.8000000        4
45.5000000         4
33753000           3
46000000           3
$68.4000000        3
430000000          3
27700000           3
41800000           3
42000000           3
20000000           3
27000000           3
26700000           3
63000000           3
42800000           3
$54.3000000        3
225000000          3
$32.0000000        3
27980000           3
$27000000          3
$33.8000000        3
25600000           3
52100000           3
228900000          3
320000000          3
35500000           3
282000000          3
$69.6000000        3
27500000           2
111.1000000        2
100.0000000        2
180.7000000        2
26635000           2
90.7000000         2
35.5000000         2
177.4000000        2
30232000           2
474100000          2
77.9000000         2
55600000           2
40.8000000         2
31689000           2
316.7000000        2
212142000          2
137499000          2
33.3000000         2
57.5000000         2
41.3000000         2
62.8000000         2
80.8000000         2
58100000           2
94.5000000         2
$37000000          2
111.9000000        2
130.4000000        2
218.1000000        2
37.4000000         2
50.8000000         2
41279000           2
91.9000000         2
175000000          2
43.8000000         2
48300000           2
48.7000000         2
68000000           2
$33.3000000        2
32.7000000         2
$113.2000000       2
$417.4000000       2
34.7000000         2
$93.7000000        2
63400000           2
14.6000000         2
81700000           2
43.4000000         2
$185.5000000       2
40295000           2
85.2000000         2
$142.6000000       2
97.8000000         2
93.4000000         2
40904000           2
61.1000000         2
39599000           2
$108.6000000       2
45046000           2
$217.3000000       2
$77.7000000        2
231.5000000        2
56.3000000         2
$176.3000000       2
$215.7000000       2
58460000           2
195900000          2
12.1000000         2
5.8000000          2
69.9000000         2
83400000           2
151448000          2
$80.3000000        2
51.9000000         2
57407000           2
77.5000000         2
$54.7000000        2
30.2000000         2
292000000          2
$55.2000000        2
$79.3000000        2
$34.1000000        2
50275000           2
84000000           2
31398000           2
471.1000000        2
27103000           2
77.4000000         2
55038000           2
457.4000000        2
411.5000000        2
32400000           2
40066000           2
8.7000000          2
75.4000000         2
58.3000000         2
45526000           2
27499000           2
55.0000000         2
30999000           2
37.9000000         2
122.5000000        2
$127.3000000       2
52.7000000         2
53.8000000         2
25400000           2
$32.6000000        2
31006000           2
186000000          2
54000000           2
40.2000000         2
25800000           2
$25.8000000        2
151.3000000        2
49455000           2
50.1000000         2
$122.5000000       2
107.5000000        2
43999000           2
42.5000000         2
34.1000000         2
450.2000000        2
32744000           2
50756000           2
42.9000000         2
145515000          2
473.8000000        2
531800000          2
$279.5000000       2
46.9000000         2
30465000           2
60.2000000         2
349999000          2
45984000           2
$84.5000000        2
130600000          2
147500000          2
36900000           2
31008000           2
36.7000000         2
87.8000000         2
41719000           2
74600000           2
72300000           2
70.7000000         2
$57.9000000        2
78.1000000         2
$50.5000000        2
218.7000000        2
325.2000000        2
82600000           2
34.0000000         2
224.9000000        2
30432000           2
147.5000000        2
68500000           2
59.2000000         2
52.2000000         2
194.4000000        2
$81000000          2
64.6000000         2
108.6000000        2
187000000          2
433000000          2
43.3000000         2
41.1000000         2
98.7000000         2
92.7000000         2
49100000           2
247000000          2
30.3000000         2
11200000           2
166.6000000        2
355.3000000        2
34.4000000         2
201.7000000        2
59.8000000         2
65.5000000         2
82.4000000         2
82400000           2
86600000           2
45793000           2
222500000          2
$35.0000000        2
83500000           2
28493000           2
49316000           2
472.3000000        2
32891000           2
34.6000000         2
44469000           2
122.2000000        2
229.2000000        2
67.9000000         2
43.9000000         2
64.2000000         2
30.6000000         2
53500000           2
51.2000000         2
34789000           2
95829000           2
30.9000000         2
42.7000000         2
80859000           2
$292.3000000       2
$31.9000000        2
59800000           2
157949000          2
145800000          2
38.8000000         2
36854000           2
330.4000000        2
570000000          2
97800000           2
114.1000000        2
49934000           2
64684000           2
39.1000000         2
98.9000000         2
45.1000000         2
93.8000000         2
57.8000000         2
$37.3000000        2
50.0000000         2
38944000           2
193.9000000        2
$53.0000000        2
42079000           2
19000000           2
44.1000000         2
$41.4000000        2
79.5000000         2
29282000           2
48.4000000         2
133333000          2
25790000           2
32300000           2
49300000           2
297866000          2
93.5000000         2
295715000          2
87.5000000         2
34.3000000         2
479242000          2
36.3000000         2
303000000          2
63.5000000         2
67600000           2
75.5000000         2
31.7000000         2
44.9000000         2
493.7000000        2
47.8000000         2
40770000           2
589422000          2
34000000           2
671400000          2
$28.0000000        2
159000000          2
390000000          2
46.5000000         2
53.9000000         2
254000000          2
62900000           2
$317.5000000       2
30.7000000         2
385.2000000        2
275000000          2
319.2000000        2
40.7000000         2
234.9000000        2
306.2000000        2
205000000          2
83.9000000         2
303.8000000        2
388000000          2
76400000           2
276.1000000        2
25900000           2
48.9000000         2
35.1000000         2
170.5000000        2
293.7000000        2
434.5000000        2
55.2000000         2
593600000          2
193.8000000        2
184.4000000        2
37400000           2
318.3000000        2
32.9000000         2
61.3000000         2
47.7000000         2
58.6000000         2
36.8000000         2
69300000           2
31.8000000         2
108400000          2
156.7000000        2
109.4000000        2
64.8000000         2
36.1000000         2
40677000           2
40964000           2
54.7000000         2
232.7000000        2
214103000          2
448.2000000        2
27800000           2
215.9000000        2
4.5000000          2
294.4000000        2
38005000           2
85.4000000         2
29167000           2
365963000          2
56043000           2
205960000          2
31397000           2
66.1000000         2
39.3000000         2
33.5000000         2
35.8000000         2
33100000           2
249200000          2
49.1000000         2
259.4000000        2
86.6000000         2
38520000           2
407000000          2
45.2000000         2
52.4000000         2
134.4000000        2
92.4000000         2
267.5000000        2
52.1000000         2
131000000          2
$47000000          2
$26000000          2
137.5000000        2
256.7000000        2
$34.5000000        2
437.9000000        2
61547000           2
29297000           2
130.9000000        2
30200000           2
389.4000000        2
220.0000000        2
451000000          2
57.2000000         2
40396000           2
43.2000000         2
146.1000000        2
38.5000000         2
189.3000000        2
98.5000000         2
436.2000000        2
87930000           2
128.7000000        2
$468.1000000       2
33673000           2
34018000           2
82.9000000         2
462277000          2
133000000          2
141.8000000        2
35022000           2
47.5000000         2
356.8000000        2
362.6000000        2
26800000           2
68830000           2
129000000          2
60100000           2
88.5000000         2
215000000          2
119400000          2
62.6000000         2
100.4000000        2
266600000          2
30800000           2
43.5000000         2
36056000           2
61700000           2
25700000           2
34289000           2
155.2000000        2
175.9000000        2
29079000           2
69000000           2
107.6000000        2
182000000          2
27361000           2
131250000          2
397924000          2
95.7000000         2
29944000           2
35.3000000         2
54.3000000         2
71.9000000         2
149400000          2
257.2000000        2
51902000           2
53.5000000         2
28752000           2
379.7000000        2
700000000          2
30316000           2
59.5000000         2
39612000           2
34.5000000         2
208400000          2
40700000           2
103000000          2
135000000          2
63800000           2
$34.9000000        2
44215000           2
33.2000000         2
75400000           2
81.5000000         2
318363000          2
39886000           2
44.4000000         2
126.5000000        2
64.4000000         2
56.1000000         2
78.5000000         2
31.3000000         2
209000000          2
251.2000000        2
28301000           2
35.7000000         2
217.9000000        2
374000000          2
290000000          2
188.4000000        2
250.5000000        2
25996000           2
65100000           2
96.9000000         2
89000000           2
56.4000000         2
162.3000000        2
63.2000000         2
31.6000000         2
45.3000000         2
46497000           2
245000000          2
354300000          2
68.2000000         2
218000000          2
99.3000000         2
$30000000          2
45490000           2
56900000           2
36.6000000         2
29419000           2
81.4000000         2
215.7000000        2
242.9000000        2
308.5000000        2
380000000          2
81.9000000         2
392.3000000        2
485452000          2
131.1000000        2
45.0000000         2
40.4000000         2
34634000           2
294.8000000        2
417000000          2
39761000           2
48.3000000         2
30132000           2
40.6000000         2
37.0000000         2
339000000          2
115.5000000        2
469.7000000        2
455.1000000        2
121.6000000        2
187.1000000        2
$25.6000000        2
9000000            2
87.4000000         2
162.9000000        2
112.5000000        2
478.5000000        2
49901000           2
70.1000000         2
88.4000000         2
32.2000000         2
60600000           2
307.5000000        2
54.4000000         2
89.2000000         2
51.8000000         2
48.6000000         2
37752000           2
173000000          2
36.5000000         2
56.6000000         2
83176000           2
348.4000000        2
190000000          2
387300000          2
380.2000000        2
82.1000000         2
48159000           2
45450000           2
33915000           2
38.7000000         2
63.3000000         2
27200000           2
44500000           2
91000000           2
333000000          2
311.6000000        2
387.3000000        2
109.1000000        2
68.5000000         2
26057000           2
40816000           2
270000000          2
29878000           2
25200000           2
29724000           2
39430000           2
49.9000000         2
168.4000000        2
170500000          2
51620000           2
64736000           2
51021000           2
72.7000000         2
32093000           2
492600000          2
75900000           2
31158000           2
45.8000000         2
126000000          2
149.6000000        2
86.5000000         2
478.3000000        2
46.0000000         2
46.6000000         2
72.4000000         2
240000000          2
51.1000000         2
32100000           2
52.5000000         2
$30.0000000        2
190.1000000        2
44900000           2
33850000           2
$54000000          2
34353000           2
27106000           2
148.5000000        2
28071000           2
79.3000000         2
203.7000000        2
65.2000000         2
191.7000000        2
121000000          2
206000000          2
681200000          2
29236000           2
112000000          2
387.5000000        2
310000000          2
286.1000000        2
120.8000000        2
30402000           2
188.2000000        2
61000000           2
45400000           2
517208000          2
57100000           2
95000000           2
69.6000000         2
65498000           2
38425000           2
53781000           2
308.0000000        2
97000000           2
46427000           2
119.1000000        2
318300000          2
149281000          2
149.3000000        2
87000000           2
55.4000000         2
53.7000000         2
$61.3000000        2
73.7000000         2
251.1000000        2
52862000           2
$457.6000000       2
122200000          1
$32.5000000        1
34100000           1
96800000           1
$29.6000000        1
42200000           1
92300000           1
$29.9000000        1
$80.0000000        1
$29.4000000        1
$71.2000000        1
75700000           1
274800000          1
51883000           1
27856000           1
49416000           1
44354000           1
263400000          1
189900000          1
28600000           1
260000000          1
148500000          1
68700000           1
$35.6000000        1
54400000           1
45500000           1
160000000          1
$40.0000000        1
48888000           1
550000000          1
$45.6000000        1
214000000          1
118300000          1
$43000000          1
70200000           1
81600000           1
$27.5000000        1
210700000          1
166900000          1
142000000          1
53637000           1
37300000           1
438300000          1
$100.0000000       1
$44.1000000        1
50967000           1
42400000           1
486000000          1
39979000           1
405500000          1
36569000           1
$341.6000000       1
51059000           1
153600000          1
$50.0000000        1
$32.2000000        1
34493000           1
$45.5000000        1
1000000            1
28082000           1
98000000           1
295000000          1
29600000           1
30037000           1
$120.0000000       1
44800000           1
$54.0000000        1
$68.3000000        1
67900000           1
$204000000         1
507300000          1
$39.4000000        1
28199000           1
$50000000          1
63300000           1
76100000           1
31782000           1
$108.2000000       1
26090000           1
48500000           1
65300000           1
$35000000          1
501400000          1
185800000          1
126300000          1
29100000           1
31300000           1
$33.4000000        1
$47.0000000        1
533000000          1
356000000          1
$48.0000000        1
41400000           1
$55000000          1
$28.9000000        1
66700000           1
$133000000         1
249500000          1
324800000          1
139990000          1
135800000          1
33500000           1
445600000          1
$59.8000000        1
$358.0000000       1
78600000           1
52085000           1
497000000          1
26552000           1
41000000           1
40084000           1
365000000          1
328700000          1
234649000          1
250810000          1
570190000          1
51324000           1
44939000           1
51200000           1
55025000           1
$73.3000000        1
31100000           1
$38.0000000        1
35822000           1
40517000           1
$300000000         1
461700000          1
108600000          1
32080000           1
32436000           1
81000000           1
$600000000         1
$90.0000000        1
290400000          1
59200000           1
$191.0000000       1
58500000           1
68200000           1
$37.5000000        1
161000000          1
137500000          1
119000000          1
$33000000          1
53906000           1
67400000           1
$69.3000000        1
49900000           1
$30.2000000        1
60700000           1
142500000          1
12600000           1
51400000           1
52400000           1
$64.1000000        1
$72.5000000        1
516900000          1
$59.7000000        1
143800000          1
$42.8000000        1
$156.5000000       1
116000000          1
$119.2000000       1
222208000          1
72400000           1
$590000000         1
54300000           1
57500000           1
86000000           1
43408000           1
29500000           1
492946000          1
$41.8000000        1
$85000000          1
204499000          1
297000000          1
37100000           1
26900000           1
391000000          1
76200000           1
$40.2000000        1
537000000          1
$25.4000000        1
30900000           1

In [70]:
# Removing '.' and '$' from the new field 'revenue_new' and casting it as integer type:
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].str.replace('[$.]', '', regex =True)
df_clean['revenue_cleaned'] = df_clean['revenue_cleaned'].astype(int)

In [71]:
# Getting statistical values into the variable 'stats':
stats = df_clean.describe().reset_index()
print(type(stats))
print(stats)

<class 'pandas.core.frame.DataFrame'>
   index  revenue_cleaned
0  count     5.518000e+03
1   mean     2.454098e+08
2    std     6.178613e+08
3    min     0.000000e+00
4    25%     0.000000e+00
5    50%     3.100000e+07
6    75%     2.445000e+08
7    max     5.820000e+09

In [72]:
# Getting the median value for revenue:
median_val  = df_clean['revenue_cleaned'].median()
median_val = pd.Series(median_val)
print(type(median_val))
print(median_val)

<class 'pandas.core.series.Series'>
0    31000000.0
dtype: float64

In [73]:
# Concateneting 'median_val' to the 'stats' dataframe:
stats= pd.concat([stats, median_val.to_frame()], ignore_index=True)
print(stats)

   index  revenue_cleaned           0
0  count     5.518000e+03         NaN
1   mean     2.454098e+08         NaN
2    std     6.178613e+08         NaN
3    min     0.000000e+00         NaN
4    25%     0.000000e+00         NaN
5    50%     3.100000e+07         NaN
6    75%     2.445000e+08         NaN
7    max     5.820000e+09         NaN
8    NaN              NaN  31000000.0

In [74]:
# Renaming column 'index' as 'Stats':
stats.rename(columns= {'index':'revenue_stats'}, inplace= True)

In [75]:
stats.rename(columns= {'revenue_cleaned': 'values'}, inplace= True)

In [76]:
# Updating the median value correctly
stats['revenue_stats'][8] = 'median'
stats['values'][8] = stats[0][8]
stats.drop(columns= [0], inplace= True)

C:\Users\yania\AppData\Local\Temp\ipykernel_24896\1429440511.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_24896\1429440511.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['revenue_stats'][8] = 'median'
C:\Users\yania\AppData\Local\Temp\ipykernel_24896\1429440511.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  stats['values'][8] = stats[0][8]
C:\Users\yania\AppData\Local\Temp\ipykernel_24896\1429440511.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['values'][8] = stats[0][8]

In [77]:
stats

  revenue_stats        values
0         count  5.518000e+03
1          mean  2.454098e+08
2           std  6.178613e+08
3           min  0.000000e+00
4           25%  0.000000e+00
5           50%  3.100000e+07
6           75%  2.445000e+08
7           max  5.820000e+09
8        median  3.100000e+07

In [ ]:
# Print CSV stats (mean, median, min, max, etc.,):
stats = stats.to_csv('stats_values.csv')

In [ ]:
# Print a specific column:
print(df_clean['Employee Size'])

In [ ]:
# Print unique values:
print(df_clean['Employee Size'].value_counts().unique)

In [ ]:
df_clean['Company'] = df_clean['Company'].astype(str)

array(['13WHAM ABC', '20/20 CUSTOM MOLDED PLASTICS', '3 UNDER 3', ...,
       'ZUMBIEL', '0',
       'Applied filters:\nCompany Count is greater than or equal to 2'],
      dtype=object)

np.int64(5536)

In [ ]:
# Filter on row:
companies_w_million_revenue = df_clean[df_clean['revenue_cleaned'] >= 1000000]

Slicing:

In [ ]:
# Slicing: Top 10 companies with >=1M revenue
companies_w_million_revenue[['Company', 'revenue_cleaned']][:10]

In [ ]:
# Update column:
df_clean['Revenue'] = df_clean['revenue_cleaned']

In [ ]:
# Drop columns:
df_clean.drop(columns = ['revenue_cleaned'], inplace = True)

In [ ]:
# Create calculated columns:

In [ ]:
# Delete/output