In [4]:
import pandas as pd

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
df = pd.read_csv('reviews.csv')

In [7]:
df.head()

  ProductID   ReviewID                                             Review
0   HT-1000  100000000  Three start. I have some issues like some keys...
1   HT-1001  100000001  Heating and not wake up. Check twice when buy ...
2   HT-1002  100000002  2nd hand laptops!!! The laptop I received alre...
3   HT-1003  100000003  Review: BEST LAPTOP IN A PRICE SEGMENT OF Rs 5...
4   HT-1010  100000004  Review: second hand product. don't buy this. I...

Given a dataset of product reviews, with the goal of predicting the sentiment (positive or negative) of each review.

1. **TF-IDF Vectorization:** Convert raw text into a TF-IDF matrix, capturing the importance of words in context to the document corpus.
2. **Sentiment Score:** Utilize a sentiment analysis library to compute sentiment scores for each review and create a feature from these scores.
3. **N-Grams:** Create features based on the presence of specific n-grams that are hypothesized to be strong indicators of positive or negative sentiment.

Python, NLTK or similar libraries for natural language processing. For example: sklearn.feature_extraction.text using TfidfVectorizer

### step 1:

In [11]:
vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(df['Review'])

In [ ]:
print(x.toarray())
x.shape

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.25836133 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

(85, 537)

In [24]:
df_data = pd.DataFrame(x.toarray(), columns= vectorizer.get_feature_names_out())
df_data.head()

    10  2017       2nd  50k        55  ...  would  wrking  yes  you  your
0  0.0   0.0  0.000000  0.0  0.000000  ...    0.0     0.0  0.0  0.0   0.0
1  0.0   0.0  0.000000  0.0  0.000000  ...    0.0     0.0  0.0  0.0   0.0
2  0.0   0.0  0.258361  0.0  0.000000  ...    0.0     0.0  0.0  0.0   0.0
3  0.0   0.0  0.000000  0.0  0.420583  ...    0.0     0.0  0.0  0.0   0.0
4  0.0   0.0  0.000000  0.0  0.000000  ...    0.0     0.0  0.0  0.0   0.0

[5 rows x 537 columns]

### Step 2:

In [26]:
from textblob import TextBlob

In [33]:
df['sentiment'] = df['Review'].apply(lambda review: TextBlob(review).sentiment.polarity)

In [31]:
df.head()

  ProductID  ...  sentiment
0   HT-1000  ...  -0.025000
1   HT-1001  ...   0.000000
2   HT-1002  ...  -0.042614
3   HT-1003  ...   1.000000
4   HT-1010  ...   0.000000

[5 rows x 4 columns]

In [38]:
print(df.groupby('sentiment').first())

          ProductID  ...                                             Review
sentiment            ...
-1.0000     HT-1007  ...  Review: Worst laptop ever not for student use ...
-0.9550     HT-1020  ...  Review: very bad. My product is not working wh...
-0.7000     HT-1030  ...  Review: It’s been just 2 months and the device...
-0.7000     HT-1010  ...  Review:  have had extremely bad experiences wi...
-0.6350     HT-1001  ...  Review: very poor. disappointed. Defective pro...
...             ...  ...                                                ...
 0.8275     HT-1010  ...  Review: Very good and light weight laptop. Thi...
 0.8500     HT-1050  ...  Review: There is no comparison for apple produ...
 0.8700     HT-1007  ...  Review: Very good product. Perfectly packed & ...
 0.9000     HT-1000  ...  Review: Best rate got from market value for mo...
 1.0000     HT-1003  ...  Review: BEST LAPTOP IN A PRICE SEGMENT OF Rs 5...

[66 rows x 3 columns]

In [39]:
df['sentiment'].value_counts()

sentiment
0.000000    8
0.850000    4
0.800000    3
0.750000    2
1.000000    2
           ..
0.350000    1
0.700000    1
0.150000    1
0.673333    1
0.700000    1
Name: count, Length: 66, dtype: int64

In [41]:
df['sentiment'].count()

np.int64(85)